// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWE-mGz9Ul54dfVafFyLWQtVcsG7ScHU',
    appId: '1:220639546966:web:1917cc6cc6dfa8a879b5f7',
    messagingSenderId: '220639546966',
    projectId: 'budget-planner-4ce1e',
    authDomain: 'budget-planner-4ce1e.firebaseapp.com',
    storageBucket: 'budget-planner-4ce1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTT108BA0PyW_J8zrhIWJD8T7D9WEH1k',
    appId: '1:220639546966:android:61a671f32c1febf179b5f7',
    messagingSenderId: '220639546966',
    projectId: 'budget-planner-4ce1e',
    storageBucket: 'budget-planner-4ce1e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWE-mGz9Ul54dfVafFyLWQtVcsG7ScHU',
    appId: '1:220639546966:web:69a3cbe15737f17f79b5f7',
    messagingSenderId: '220639546966',
    projectId: 'budget-planner-4ce1e',
    authDomain: 'budget-planner-4ce1e.firebaseapp.com',
    storageBucket: 'budget-planner-4ce1e.firebasestorage.app',
  );
}
